import { Connection, Keypair, PublicKey, SystemProgram } from '@solana/web3.js';
import { Program, AnchorProvider, Wallet, BN } from '@coral-xyz/anchor';
import crypto from 'crypto';
import type { ISolanaService, SolanaAgreement, SolanaInitResult, SolanaReleaseRentResult, SolanaSettlementResult, SolanaTopUpRentTxResult } from './interface';
import { getStateLabel } from './types';

// IDL is generated by `anchor build` — must exist at this path before running
// eslint-disable-next-line @typescript-eslint/no-require-imports
const IDL = require('../../target/idl/rentsmart.json') as Record<string, unknown>;

export class SolanaService implements ISolanaService {
  private readonly connection: Connection;
  private readonly authority: Keypair;
  private readonly platformWallet: PublicKey;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private readonly program: Program<any>;
  private readonly programId: PublicKey;

  constructor() {
    const rpcUrl = process.env.SOLANA_RPC_URL ?? 'https://api.devnet.solana.com';
    const programId = process.env.SOLANA_PROGRAM_ID;
    const rawKeypair = process.env.SOLANA_AUTHORITY_KEYPAIR;
    const platformPubkey = process.env.PLATFORM_SOLANA_PUBKEY;

    if (!programId) {
      throw new Error('SOLANA_PROGRAM_ID env variable is required');
    }
    if (!rawKeypair) {
      throw new Error('SOLANA_AUTHORITY_KEYPAIR env variable is required');
    }
    if (!platformPubkey) {
      throw new Error('PLATFORM_SOLANA_PUBKEY env variable is required');
    }

    const keypairBytes = JSON.parse(rawKeypair) as number[];
    if (keypairBytes.length !== 64) {
      throw new Error('SOLANA_AUTHORITY_KEYPAIR must be a JSON array of 64 bytes');
    }

    this.programId = new PublicKey(programId);
    this.authority = Keypair.fromSecretKey(Uint8Array.from(keypairBytes));
    this.platformWallet = new PublicKey(platformPubkey);
    this.connection = new Connection(rpcUrl, 'confirmed');

    const wallet = new Wallet(this.authority);
    const provider = new AnchorProvider(this.connection, wallet, { commitment: 'confirmed' });
    this.program = new Program(IDL, provider);
  }

  findPDA(contractId: string): { pda: string; bump: number } {
    const [pda, bump] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );
    return { pda: pda.toBase58(), bump };
  }

  async initializeContract(
    contractId: string,
    contractHash: Buffer,
    depositLamports: number,
    landlordPubkey: string,
  ): Promise<SolanaInitResult> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    // On-chain contract_id is [u8; 32] — first 32 bytes of the UUID ASCII string
    const contractIdBytes = Array.from(Buffer.from(contractId).subarray(0, 32));
    const contractHashArray = Array.from(contractHash.subarray(0, 32));

    const programMethods = (this.program as any).methods;

    const txSignature = await programMethods
      .initialize(contractIdBytes, contractHashArray, new BN(depositLamports))
      .accounts({
        agreement: pda,
        authority: this.authority.publicKey,
        landlord: new PublicKey(landlordPubkey),
        platform: this.platformWallet,
        systemProgram: SystemProgram.programId,
      })
      .signers([this.authority])
      .rpc();

    return {
      tx_signature: txSignature,
      pda_address: pda.toBase58(),
      explorer_url: `https://explorer.solana.com/tx/${txSignature}?cluster=devnet`,
    };
  }

  async buildLockDepositTx(
    contractId: string,
    tenantPubkey: string,
  ): Promise<{ serialized_tx: string }> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    // Build the transaction without signing — tenant will sign on their device
    const programMethods = (this.program as any).methods;

    const tx = await programMethods
      .lockDeposit()
      .accounts({
        agreement: pda,
        tenant: new PublicKey(tenantPubkey),
        systemProgram: SystemProgram.programId,
      })
      .transaction();

    const { blockhash } = await this.connection.getLatestBlockhash();
    tx.recentBlockhash = blockhash;
    tx.feePayer = new PublicKey(tenantPubkey);

    // Serialize without requiring all signatures — tenant signature missing intentionally
    const serialized = tx.serialize({ requireAllSignatures: false });
    return { serialized_tx: serialized.toString('base64') };
  }

  async recordCheckin(
    contractId: string,
    imageHash: Buffer,
    _landlordPubkey: string,
  ): Promise<{ tx_signature: string }> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    const imageHashArray = Array.from(imageHash.subarray(0, 32));

    const programMethods = (this.program as any).methods;

    const txSignature = await programMethods
      .recordCheckin(imageHashArray)
      .accounts({
        agreement: pda,
        authority: this.authority.publicKey,
      })
      .signers([this.authority])
      .rpc();

    return { tx_signature: txSignature };
  }

  async recordCheckout(
    contractId: string,
    imageHash: Buffer,
    _tenantPubkey: string,
  ): Promise<{ tx_signature: string }> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    const imageHashArray = Array.from(imageHash.subarray(0, 32));

    const programMethods = (this.program as any).methods;

    const txSignature = await programMethods
      .recordCheckout(imageHashArray)
      .accounts({
        agreement: pda,
        authority: this.authority.publicKey,
      })
      .signers([this.authority])
      .rpc();

    return { tx_signature: txSignature };
  }

  async buildTopUpRentTx(
    contractId: string,
    tenantPubkey: string,
    rentLamports: number,
    months: number,
  ): Promise<SolanaTopUpRentTxResult> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    // Tenant pre-funds escrow: rent × 1.005 per month (includes their 0.5% fee share)
    const PLATFORM_FEE_BPS = 50;
    const feePerMonth = Math.floor((rentLamports * PLATFORM_FEE_BPS) / 10_000);
    const perMonthTotal = rentLamports + feePerMonth;
    const amountLamports = perMonthTotal * months;

    const programMethods = (this.program as any).methods;

    const tx = await programMethods
      .topUpRent(new BN(amountLamports))
      .accounts({
        agreement: pda,
        tenant: new PublicKey(tenantPubkey),
        systemProgram: SystemProgram.programId,
      })
      .transaction();

    const { blockhash } = await this.connection.getLatestBlockhash();
    tx.recentBlockhash = blockhash;
    tx.feePayer = new PublicKey(tenantPubkey);

    const serialized = tx.serialize({ requireAllSignatures: false });
    return {
      serialized_tx: serialized.toString('base64'),
      amount_lamports: amountLamports,
      months_covered: months,
      fee_lamports: feePerMonth * months,
    };
  }

  async releaseMonthlyRent(
    contractId: string,
    rentLamports: number,
    landlordPubkey: string,
    platformPubkey: string,
  ): Promise<SolanaReleaseRentResult> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    const PLATFORM_FEE_BPS = 50;
    const feePerSide = Math.floor((rentLamports * PLATFORM_FEE_BPS) / 10_000);
    const landlordAmount = rentLamports - feePerSide;
    const platformFee = feePerSide * 2;

    const programMethods = (this.program as any).methods;

    const txSignature = await programMethods
      .releaseMonthlyRent(new BN(rentLamports))
      .accounts({
        agreement: pda,
        authority: this.authority.publicKey,
        landlord: new PublicKey(landlordPubkey),
        platform: new PublicKey(platformPubkey),
      })
      .signers([this.authority])
      .rpc();

    return {
      tx_signature: txSignature,
      landlord_amount: landlordAmount,
      platform_fee: platformFee,
      explorer_url: `https://explorer.solana.com/tx/${txSignature}?cluster=devnet`,
    };
  }

  async executeSettlement(
    contractId: string,
    settlementHash: Buffer,
    tenantAmount: number,
    landlordAmount: number,
    tenantPubkey: string,
    landlordPubkey: string,
  ): Promise<SolanaSettlementResult> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    const settlementHashArray = Array.from(settlementHash.subarray(0, 32));

    const programMethods = (this.program as any).methods;

    const txSignature = await programMethods
      .executeSettlement(
        settlementHashArray,
        new BN(tenantAmount),
        new BN(landlordAmount),
      )
      .accounts({
        agreement: pda,
        authority: this.authority.publicKey,
        tenant: new PublicKey(tenantPubkey),
        landlord: new PublicKey(landlordPubkey),
      })
      .signers([this.authority])
      .rpc();

    return {
      tx_signature: txSignature,
      explorer_url: `https://explorer.solana.com/tx/${txSignature}?cluster=devnet`,
    };
  }

  async getAgreement(contractId: string): Promise<SolanaAgreement | null> {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from('rental'), Buffer.from(contractId).subarray(0, 32)],
      this.programId,
    );

    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const account = await (this.program.account as any).rentalAgreement.fetch(pda);
      return {
        contract_id: Buffer.from(account.contractId as number[])
          .toString('utf8')
          .replace(/\0/g, ''),
        contract_hash: Buffer.from(account.contractHash as number[]).toString('hex'),
        deposit_lamports: (account.depositLamports as BN).toNumber(),
        prepaid_rent_lamports: (account.prepaidRentLamports as BN).toNumber(),
        landlord: account.landlord.toBase58(),
        authority: account.authority.toBase58(),
        platform_wallet: account.platformWallet.toBase58(),
        tenant: account.tenant.toBase58(),
        state: getStateLabel(account.state),
        checkin_hash: Buffer.from(account.checkinHash as number[]).toString('hex'),
        checkout_hash: Buffer.from(account.checkoutHash as number[]).toString('hex'),
        settlement_hash: Buffer.from(account.settlementHash as number[]).toString('hex'),
        created_at: (account.createdAt as BN).toNumber(),
        explorer_url: `https://explorer.solana.com/address/${pda.toBase58()}?cluster=devnet`,
      };
    } catch {
      // Account not found (contract not yet initialized or wrong network)
      return null;
    }
  }

  hashImages(imageHashes: string[]): Buffer {
    const combined = imageHashes.join('');
    return crypto.createHash('sha256').update(combined).digest();
  }

  eurToLamports(eurAmount: number): number {
    // Uses EUR_SOL_RATE env variable (SOL per 1 EUR).
    // Default 0.01 is conservative for devnet demos — not a real exchange rate.
    // In production, fetch from a Pyth Network price oracle before calling this.
    const solPerEur = parseFloat(process.env.EUR_SOL_RATE ?? '0.01');
    return Math.round(eurAmount * solPerEur * 1_000_000_000);
  }
}
