import { AuditEvent, AuditTrailResponse, AuditEventType } from '@rentsmart/contracts';

class AuditService {
  async getAuditTrail(contractId: string): Promise<AuditTrailResponse> {
    const events: AuditEvent[] = [
      {
        id: 'event-001',
        contract_id: contractId,
        event_type: 'CONTRACT_CREATED' as AuditEventType,
        actor_id: 'landlord-user-id',
        actor_role: 'landlord' as const,
        data: {
          property_address: 'Kneza Miloša 1, Beograd',
          deposit_amount_eur: 1200,
          rent_monthly_eur: 600,
        },
        event_hash: 'hash-001',
        previous_hash: null,
        created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-002',
        contract_id: contractId,
        event_type: 'INVITE_SENT' as AuditEventType,
        actor_id: 'landlord-user-id',
        actor_role: 'landlord' as const,
        data: {
          invite_code: 'ABC123DEF',
          sent_to_phone: '+38161234567',
        },
        event_hash: 'hash-002',
        previous_hash: 'hash-001',
        created_at: new Date(Date.now() - 89 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-003',
        contract_id: contractId,
        event_type: 'CONTRACT_ACCEPTED' as AuditEventType,
        actor_id: 'tenant-user-id',
        actor_role: 'tenant' as const,
        data: {
          accepted_at: new Date(Date.now() - 88 * 24 * 60 * 60 * 1000).toISOString(),
        },
        event_hash: 'hash-003',
        previous_hash: 'hash-002',
        created_at: new Date(Date.now() - 88 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-004',
        contract_id: contractId,
        event_type: 'DEPOSIT_LOCKED' as AuditEventType,
        actor_id: null,
        actor_role: 'system' as const,
        data: {
          solana_pda: 'SolanaWalletAddress123abc',
          tx_signature: 'SolanaTransactionSignature123',
        },
        event_hash: 'hash-004',
        previous_hash: 'hash-003',
        created_at: new Date(Date.now() - 88 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-005',
        contract_id: contractId,
        event_type: 'CHECKIN_STARTED' as AuditEventType,
        actor_id: 'landlord-user-id',
        actor_role: 'landlord' as const,
        data: {
          gps_location: { lat: 44.8176, lng: 20.4554 },
          device_id: 'device-landlord-123',
        },
        event_hash: 'hash-005',
        previous_hash: 'hash-004',
        created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-006',
        contract_id: contractId,
        event_type: 'CHECKIN_IMAGE_CAPTURED' as AuditEventType,
        actor_id: 'landlord-user-id',
        actor_role: 'landlord' as const,
        data: {
          room: 'Living Room',
          image_hash: 'photo-hash-001',
          image_index: 1,
        },
        event_hash: 'hash-006',
        previous_hash: 'hash-005',
        created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-007',
        contract_id: contractId,
        event_type: 'CHECKIN_IMAGE_CAPTURED' as AuditEventType,
        actor_id: 'landlord-user-id',
        actor_role: 'landlord' as const,
        data: {
          room: 'Bedroom',
          image_hash: 'photo-hash-002',
          image_index: 2,
        },
        event_hash: 'hash-007',
        previous_hash: 'hash-006',
        created_at: new Date(Date.now() - 29.95 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-008',
        contract_id: contractId,
        event_type: 'CHECKIN_COMPLETED' as AuditEventType,
        actor_id: 'landlord-user-id',
        actor_role: 'landlord' as const,
        data: {
          room_count: 2,
          total_images: 2,
        },
        event_hash: 'hash-008',
        previous_hash: 'hash-007',
        created_at: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-009',
        contract_id: contractId,
        event_type: 'CHECKIN_APPROVED' as AuditEventType,
        actor_id: 'tenant-user-id',
        actor_role: 'tenant' as const,
        data: {
          approval_timestamp: new Date(Date.now() - 28.5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        event_hash: 'hash-009',
        previous_hash: 'hash-008',
        created_at: new Date(Date.now() - 28.5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-010',
        contract_id: contractId,
        event_type: 'CHECKOUT_STARTED' as AuditEventType,
        actor_id: 'tenant-user-id',
        actor_role: 'tenant' as const,
        data: {
          gps_location: { lat: 44.8176, lng: 20.4554 },
          device_id: 'device-tenant-456',
        },
        event_hash: 'hash-010',
        previous_hash: 'hash-009',
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-011',
        contract_id: contractId,
        event_type: 'CHECKOUT_IMAGE_CAPTURED' as AuditEventType,
        actor_id: 'tenant-user-id',
        actor_role: 'tenant' as const,
        data: {
          room: 'Living Room',
          image_hash: 'photo-hash-003',
          image_index: 1,
        },
        event_hash: 'hash-011',
        previous_hash: 'hash-010',
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-012',
        contract_id: contractId,
        event_type: 'CHECKOUT_COMPLETED' as AuditEventType,
        actor_id: 'tenant-user-id',
        actor_role: 'tenant' as const,
        data: {
          room_count: 1,
          total_images: 1,
        },
        event_hash: 'hash-012',
        previous_hash: 'hash-011',
        created_at: new Date(Date.now() - 4.95 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-013',
        contract_id: contractId,
        event_type: 'CHECKOUT_APPROVED' as AuditEventType,
        actor_id: 'landlord-user-id',
        actor_role: 'landlord' as const,
        data: {
          approval_timestamp: new Date(Date.now() - 4.5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        event_hash: 'hash-013',
        previous_hash: 'hash-012',
        created_at: new Date(Date.now() - 4.5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-014',
        contract_id: contractId,
        event_type: 'LLM_ANALYSIS_STARTED' as AuditEventType,
        actor_id: null,
        actor_role: 'system' as const,
        data: {
          reference_model: 'Gemini Pro Vision',
          room_count: 4,
        },
        event_hash: 'hash-014',
        previous_hash: 'hash-013',
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-015',
        contract_id: contractId,
        event_type: 'LLM_ANALYSIS_COMPLETED' as AuditEventType,
        actor_id: null,
        actor_role: 'system' as const,
        data: {
          findings_count: 5,
          processing_time_seconds: 45,
        },
        event_hash: 'hash-015',
        previous_hash: 'hash-014',
        created_at: new Date(Date.now() - 3.9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-016',
        contract_id: contractId,
        event_type: 'RULE_ENGINE_EXECUTED' as AuditEventType,
        actor_id: null,
        actor_role: 'system' as const,
        data: {
          rules_version: '1.0',
          total_deduction_eur: 245,
          deduction_percent: 20.4,
        },
        event_hash: 'hash-016',
        previous_hash: 'hash-015',
        created_at: new Date(Date.now() - 3.8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-017',
        contract_id: contractId,
        event_type: 'SETTLEMENT_PROPOSED' as AuditEventType,
        actor_id: null,
        actor_role: 'system' as const,
        data: {
          tenant_receives_eur: 955,
          landlord_receives_eur: 245,
          deductions_count: 3,
        },
        event_hash: 'hash-017',
        previous_hash: 'hash-016',
        created_at: new Date(Date.now() - 3.7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'event-018',
        contract_id: contractId,
        event_type: 'SETTLEMENT_VIEWED' as AuditEventType,
        actor_id: 'tenant-user-id',
        actor_role: 'tenant' as const,
        data: {
          timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        event_hash: 'hash-018',
        previous_hash: 'hash-017',
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    return {
      events: events.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()),
      chain_valid: true,
    };
  }
}

export const auditService = new AuditService();
